cassandra:
  hostname: "localhost"
  port: 9042
  keyspace: "test_keyspace"
  table: "hits"
  route:
    from: "direct:xxx"
    to: "cql://${cassandra.hostname}:${cassandra.port}/${cassandra.keyspace}?cql=INSERT INTO ${cassandra.table} (id, source) values (?, ?)"
